AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploy FastAPI com OMDb API no AWS Lambda

Parameters:
  OmdbApiKey:
    Type: String
    Description: Chave de API para o OMDb

Resources:
  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      Runtime: python3.9
      CodeUri: .
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          OMDB_API_KEY: !Ref OmdbApiKey
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiEndpoint:
    Description: "URL base da API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/filme"
